TERMUX_SUBPKG_INCLUDE="
${USR}/bin/toe
${USR}/bin/tput
${USR}/bin/clear
${USR}/bin/tset
${USR}/bin/tabs
${USR}/bin/infocmp
${USR}/bin/reset
${USR}/bin/tic
${USR}/share/man/man1/toe.1.gz
${USR}/share/man/man1/tput.1.gz
${USR}/share/man/man1/clear.1.gz
${USR}/share/man/man1/tset.1.gz
${USR}/share/man/man1/tabs.1.gz
${USR}/share/man/man1/infocmp.1.gz
${USR}/share/man/man1/reset.1.gz
${USR}/share/man/man1/tic.1.gz
"
TERMUX_SUBPKG_DESCRIPTION="Tools for working with terminals"
TERMUX_SUBPKG_DEPENDS="ncurses"
